import {
  Activity,
  Boxes,
  Building2,
  ClipboardList,
  FileText,
  Coins,
  Home,
  HeartPulse,
  FileClock,
  LayoutDashboard,
  LineChart,
  LifeBuoy,
  Receipt,
  ScanLine,
  ShieldCheck,
  Truck,
  Users,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export type PharmaFlowNavStatus = 'Live' | 'Partial';
export type PharmaFlowNavAccess = 'saas-admin' | 'company-admin' | 'store-ops' | 'delivery-staff';

export interface PharmaFlowNavItem {
  title: string;
  path: string;
  summary: string;
  shortSummary: string;
  status: PharmaFlowNavStatus;
  icon: LucideIcon;
  group: 'Workspace' | 'Operations' | 'Controls';
  access: PharmaFlowNavAccess[];
}

export const pharmaFlowNavItems: PharmaFlowNavItem[] = [
  {
    title: 'Home',
    path: '/medinone/home',
    summary: 'Business home dashboard that opens the main pharmacy workflows in a calm, buyer-ready order.',
    shortSummary: 'Business home',
    status: 'Live',
    icon: Home,
    group: 'Workspace',
    access: ['saas-admin', 'company-admin', 'store-ops', 'delivery-staff'],
  },
  {
    title: 'Company Setup',
    path: '/medinone/setup',
    summary: 'Manage active store selection, branding, company profile, and account setup after signing in.',
    shortSummary: 'Store, brand, company setup',
    status: 'Live',
    icon: LayoutDashboard,
    group: 'Workspace',
    access: ['saas-admin', 'company-admin'],
  },
  {
    title: 'Readiness',
    path: '/medinone/enterprise',
    summary: 'White-label profile, operating model, capability coverage, and business readiness details.',
    shortSummary: 'Capability coverage',
    status: 'Live',
    icon: FileText,
    group: 'Workspace',
    access: ['saas-admin', 'company-admin'],
  },
  {
    title: 'SaaS Admin',
    path: '/medinone/platform',
    summary: 'Tenant roster, plans, pricing, and platform controls for SaaS ownership.',
    shortSummary: 'Tenants and pricing',
    status: 'Live',
    icon: Coins,
    group: 'Workspace',
    access: ['saas-admin'],
  },
  {
    title: 'Users & Access',
    path: '/medinone/users',
    summary: 'Create company admins, store operators, assign stores, and control who can do what from one screen.',
    shortSummary: 'Users, roles, permissions',
    status: 'Live',
    icon: Users,
    group: 'Workspace',
    access: ['saas-admin', 'company-admin'],
  },
  {
    title: 'Support',
    path: '/medinone/help',
    summary: 'Role-based support, FAQs, onboarding answers, and module explanations.',
    shortSummary: 'Support and FAQs',
    status: 'Live',
    icon: LifeBuoy,
    group: 'Workspace',
    access: ['saas-admin', 'company-admin', 'store-ops', 'delivery-staff'],
  },
  {
    title: 'Counter',
    path: '/medinone/billing',
    summary: 'Counter billing with barcode-ready medicine search, GST, substitutes, and compliance capture.',
    shortSummary: 'Billing and barcode scan',
    status: 'Live',
    icon: ScanLine,
    group: 'Operations',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Stock',
    path: '/medinone/inventory',
    summary: 'Batch stock visibility, medicine lookup, shortage detection, and FIFO-oriented stock inspection.',
    shortSummary: 'Inventory and batches',
    status: 'Live',
    icon: Boxes,
    group: 'Operations',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Purchases',
    path: '/medinone/procurement',
    summary: 'Supplier setup, manual inward entry, and CSV purchase invoice import for the active store.',
    shortSummary: 'Inward and purchase import',
    status: 'Live',
    icon: ClipboardList,
    group: 'Operations',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Bills',
    path: '/medinone/billing-history',
    summary: 'Invoice search, detailed bill review, and audit trail visibility for changes and events.',
    shortSummary: 'History and edits',
    status: 'Live',
    icon: Receipt,
    group: 'Controls',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Compliance',
    path: '/medinone/compliance',
    summary: 'Schedule H, H1, X, and narcotic reporting with Drug Inspector-ready register views.',
    shortSummary: 'Controlled drugs',
    status: 'Live',
    icon: ShieldCheck,
    group: 'Controls',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Customers',
    path: '/medinone/customers',
    summary: 'Customer search, credit visibility, loyalty actions, and patient history in one branch-friendly workspace.',
    shortSummary: 'Credit and history',
    status: 'Live',
    icon: HeartPulse,
    group: 'Operations',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Online & Delivery',
    path: '/medinone/delivery',
    summary: 'Convert online or phone medicine orders into branch deliveries, assign riders, and track delivery status from one screen.',
    shortSummary: 'Online orders and riders',
    status: 'Live',
    icon: Truck,
    group: 'Operations',
    access: ['saas-admin', 'company-admin', 'store-ops', 'delivery-staff'],
  },
  {
    title: 'GST Reports',
    path: '/medinone/reports/gst',
    summary: 'GSTR-1, GSTR-3B, shortage, expiry loss, and monthly operational reporting from store invoices.',
    shortSummary: 'GST, shortage, expiry loss',
    status: 'Live',
    icon: Activity,
    group: 'Controls',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Profit',
    path: '/medinone/reports/profit',
    summary: 'Daily sales, top sellers, slow movers, and estimated profit by manufacturer and category for the active store.',
    shortSummary: 'Sales, movement, margin',
    status: 'Live',
    icon: LineChart,
    group: 'Controls',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Expiry',
    path: '/medinone/reports/expiry-alerts',
    summary: '30, 60, and 90-day expiry buckets, at-risk stock value, and exportable alerts.',
    shortSummary: 'Expiry and shortage',
    status: 'Live',
    icon: FileClock,
    group: 'Controls',
    access: ['saas-admin', 'company-admin', 'store-ops'],
  },
  {
    title: 'Stores',
    path: '/medinone/stores',
    summary: 'Store directory, branch selection, and current multi-store readiness across HO and warehouse.',
    shortSummary: 'Store switching',
    status: 'Partial',
    icon: Building2,
    group: 'Workspace',
    access: ['saas-admin', 'company-admin'],
  },
];

export const pharmaFlowNavGroups: Array<PharmaFlowNavItem['group']> = [
  'Workspace',
  'Operations',
  'Controls',
];
