export interface PharmacyBranch {
  name: string;
  sales: number;
  orders: number;
  manager: string;
  branchId: number;
  branchAddress: string;
  branchContact?: string;
  branchFax?: string;
  branchEmail?: string;
  branchDescription?: string;
  branchImage?: ArrayBuffer;
  branchStatus?: boolean;
  branchLocation?: string;
  branchCreatedOn?: string;
  branchCreatedBy?: string;
}

export const fakeBranchData: PharmacyBranch[] = [
  {
    name: 'Sunset Pharmacy',
    sales: 550000,
    orders: 3000,
    manager: 'Emily Johnson',
    branchId: 1,
    branchAddress: '1234 Sunset Blvd, Los Angeles, CA 90001',
    branchContact: '555-123-4567',
    branchFax: '555-987-6543',
    branchEmail: 'sunsetpharmacy@example.com',
    branchDescription: 'A modern pharmacy located in the heart of Los Angeles.',
    branchStatus: true,
    branchLocation: 'Los Angeles',
    branchCreatedOn: '2023-02-15',
    branchCreatedBy: 'Alex Brown',
  },
  {
    name: 'Maple Leaf Pharmacy',
    sales: 400000,
    orders: 2000,
    manager: 'Michael Thompson',
    branchId: 2,
    branchAddress: '5678 Maple Ave, Seattle, WA 98101',
    branchContact: '555-987-6543',
    branchEmail: 'mapleleafpharmacy@example.com',
    branchDescription: 'A cozy pharmacy nestled in the heart of Seattle.',
    branchStatus: true,
    branchLocation: 'Seattle',
    branchCreatedOn: '2023-01-10',
    branchCreatedBy: 'Sarah Davis',
  },
  {
    name: 'Evergreen Pharmacy',
    sales: 650000,
    orders: 3500,
    manager: 'David Anderson',
    branchId: 3,
    branchAddress: '789 Evergreen St, Portland, OR 97201',
    branchContact: '555-111-2222',
    branchFax: '555-333-4444',
    branchEmail: 'evergreenpharmacy@example.com',
    branchDescription: 'A nature-themed pharmacy serving the community in Portland.',
    branchStatus: true,
    branchLocation: 'Portland',
    branchCreatedOn: '2023-03-20',
    branchCreatedBy: 'Jennifer Wilson',
  },
  {
    name: 'Central Pharmacy',
    sales: 700000,
    orders: 4000,
    manager: 'Oliver Smith',
    branchId: 4,
    branchAddress: '10 Central Ave, New York, NY 10001',
    branchContact: '555-555-5555',
    branchFax: '555-666-7777',
    branchEmail: 'centralpharmacy@example.com',
    branchDescription: 'A centrally located pharmacy in the heart of New York City.',
    branchStatus: true,
    branchLocation: 'New York City',
    branchCreatedOn: '2023-04-05',
    branchCreatedBy: 'Robert Johnson',
  },
  {
    name: 'Golden Gate Pharmacy',
    sales: 500000,
    orders: 2500,
    manager: 'Sophia Martinez',
    branchId: 5,
    branchAddress: '123 Golden Gate Rd, San Francisco, CA 94101',
    branchContact: '555-777-8888',
    branchEmail: 'goldengatepharmacy@example.com',
    branchDescription: 'An iconic pharmacy near the Golden Gate Bridge in San Francisco.',
    branchStatus: true,
    branchLocation: 'San Francisco',
    branchCreatedOn: '2023-02-28',
    branchCreatedBy: 'Emma Taylor',
  },
  {
    name: 'Mountain View Pharmacy',
    sales: 600000,
    orders: 3000,
    manager: 'William Brown',
    branchId: 6,
    branchAddress: '456 Mountain View Dr, Denver, CO 80202',
    branchContact: '555-999-0000',
    branchEmail: 'mountainviewpharmacy@example.com',
    branchDescription: 'A pharmacy with a scenic view nestled in the mountains of Denver.',
    branchStatus: true,
    branchLocation: 'Denver',
    branchCreatedOn: '2023-03-10',
    branchCreatedBy: 'Christopher Clark',
  },
  {
    name: 'Ocean Pharmacy',
    sales: 750000,
    orders: 4000,
    manager: 'Isabella Wilson',
    branchId: 7,
    branchAddress: '789 Ocean Ave, Miami, FL 33101',
    branchContact: '555-333-2222',
    branchFax: '555-222-1111',
    branchEmail: 'oceanpharmacy@example.com',
    branchDescription: 'A beachside pharmacy offering a serene atmosphere in Miami.',
    branchStatus: true,
    branchLocation: 'Miami',
    branchCreatedOn: '2023-05-15',
    branchCreatedBy: 'Daniel White',
  },
  {
    name: 'Palm Pharmacy',
    sales: 900000,
    orders: 4500,
    manager: 'Sophie Johnson',
    branchId: 8,
    branchAddress: '321 Palm Blvd, Orlando, FL 32801',
    branchContact: '555-444-3333',
    branchEmail: 'palmpharmacy@example.com',
    branchDescription: 'A pharmacy surrounded by palm trees offering a tropical feel in Orlando.',
    branchStatus: true,
    branchLocation: 'Orlando',
    branchCreatedOn: '2023-06-01',
    branchCreatedBy: 'James Davis',
  },
  {
    name: 'Riverfront Pharmacy',
    sales: 800000,
    orders: 4000,
    manager: 'Ethan Rodriguez',
    branchId: 9,
    branchAddress: '456 Riverfront Dr, Chicago, IL 60601',
    branchContact: '555-666-7777',
    branchFax: '555-888-9999',
    branchEmail: 'riverfrontpharmacy@example.com',
    branchDescription: 'A pharmacy with a view of the river providing a calming atmosphere in Chicago.',
    branchStatus: true,
    branchLocation: 'Chicago',
    branchCreatedOn: '2023-07-10',
    branchCreatedBy: 'Liam Wilson',
  },
  {
    name: 'Mountain Valley Pharmacy',
    sales: 700000,
    orders: 3500,
    manager: 'Charlotte Harris',
    branchId: 10,
    branchAddress: '789 Mountain Valley Rd, Phoenix, AZ 85001',
    branchContact: '555-444-3333',
    branchFax: '555-333-2222',
    branchEmail: 'mountain',
    branchDescription: 'A pharmacy nestled in the valley surrounded by mountains in Phoenix.',
    branchStatus: true,
    branchLocation: 'Phoenix',
    branchCreatedOn: '2023-08-20',
    branchCreatedBy: 'Ava Brown',
  },
];

